apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor
  labels:
    app.kubernetes.io/name: gvisor
    app.kubernetes.io/component: runtime
handler: gvisor
scheduling:
  # Optional: Use node selectors to run only on nodes with gVisor installed
  nodeSelector:
    runtime: gvisor
  # Optional: Tolerations for dedicated sandbox nodes
  tolerations:
  - key: "sandbox"
    operator: "Equal"
    value: "gvisor"
    effect: "NoSchedule"
---
# Alternative: RuntimeClass without node restrictions
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: gvisor-unrestricted
handler: gvisor
